dotnet/iot-parking/iot-parking/Models/RFIDCard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace iot_parking.Models
{
    public class RFIDCard
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(255)]
        public string CardNumber { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public CardOwner CardOwner { get; set; }

        public ICollection<Parking> Parkings { get; set; }
    }
}

dotnet/iot-parking/iot-parking/Controllers/RFIDCardsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using iot_parking.Database;
using iot_parking.Models;
using Microsoft.AspNetCore.Authorization;

namespace iot_parking.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RFIDCardsController : Controller
    {
        private readonly DatabaseContext _context;

        public RFIDCardsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: RFIDCards
        public async Task<IActionResult> Index(string? search)
        {
            var databaseContext = _context.RFIDCards.Include(c => c.CardOwner).OrderByDescending(c => c.CardOwner.IssueDate).ToList();
            if (search != null)
            {
                var filteredList = databaseContext.FindAll(
                    c => { 
                        if(c.CardOwner != null)
                            return c.CardNumber == search || c.CardOwner.Firstname == search || c.CardOwner.Lastname == search || c.CardOwner.Email == search;
                        return c.CardNumber == search;
                    });
                return View(filteredList);
            }

            return View(databaseContext);
        }

        // GET: RFIDCards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rFIDCard = await _context.RFIDCards
                .Include(c => c.CardOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rFIDCard == null)
            {
                return NotFound();
            }

            return View(rFIDCard);
        }

        // GET: RFIDCards/Create
        public async Task<IActionResult> Create(int? cardId)
        {
            TempData["pickCard"] = "Create";
            TempData["duplicateCard"] = false;
            CardOwnerRFIDCard card = new();
            card.IssueDate = System.DateTime.Now;
            card.ValidDate = System.DateTime.Now.AddDays(30);
            if (cardId != null)
            {
                var scannedCard = await _context.ScannedCards.FirstOrDefaultAsync(c => c.Id == cardId);

                if(scannedCard != null)
                {
                    card.CardNumber = scannedCard.CardNumber;
                }

            }
            return View(card);
        }

        public async Task<IActionResult> PickCard()
        {
            var cards = await _context.ScannedCards.ToListAsync();

            return View(cards);
        }

        // POST: RFIDCards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CardNumber,IsActive,HasOwner,Firstname,Lastname,Email,IssueDate,ValidDate")] CardOwnerRFIDCard card)
        {
            if (ModelState.IsValid)
            {
                RFIDCard rFIDCard = new();
                rFIDCard.CardNumber = card.CardNumber;
                rFIDCard.IsActive = card.IsActive;

                _context.Add(rFIDCard);
                try
                {
                    _context.SaveChanges();
                }
                catch (DbUpdateException)
                {
                    TempData["duplicateCard"] = true;
                    return View(card);
                }

                if (card.HasOwner) {
                    var newCard = _context.RFIDCards.FirstOrDefault(c => c.CardNumber == card.CardNumber);
                    CardOwner cardOwner = new();
                    cardOwner.Firstname = card.Firstname;
                    cardOwner.Lastname = card.Lastname;
                    cardOwner.Email = card.Email;
                    cardOwner.IssueDate = card.IssueDate;
                    cardOwner.ValidDate = card.ValidDate;
                    cardOwner.CardId = newCard.Id;

                    _context.Add(cardOwner);

                    try
                    {
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateException)
                    {
                        TempData["duplicateCard"] = true;
                        return View(card);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: RFIDCards/Edit/5
        public async Task<IActionResult> Edit(int? id, int? cardId)
        {
            if (id == null)
            {
                return NotFound();
            }

            TempData["pickCard"] = "Edit";
            TempData["carId"] = id;
            TempData["duplicateCard"] = false;

            var rFIDCard = await _context.RFIDCards
                .Include(c => c.CardOwner)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (rFIDCard == null)
            {
                return NotFound();
            }

            if (cardId != null)
            {
                var scannedCard = await _context.ScannedCards.FirstOrDefaultAsync(c => c.Id == cardId);

                if (scannedCard != null)
                {
                    ViewBag.cardNr = scannedCard.CardNumber;
                }
            }
            else
            {
                ViewBag.cardNr = rFIDCard.CardNumber;
            }

            CardOwnerRFIDCard card = new();
            card.CardNumber = rFIDCard.CardNumber;
            card.IsActive = rFIDCard.IsActive;
            
            if(rFIDCard.CardOwner != null)
            {
                card.HasOwner = true;
                card.Firstname = rFIDCard.CardOwner.Firstname;
                card.Lastname = rFIDCard.CardOwner.Lastname;
                card.Email = rFIDCard.CardOwner.Email;
                card.IssueDate = rFIDCard.CardOwner.IssueDate;
                card.ValidDate = rFIDCard.CardOwner.ValidDate;
            }
            else
            {
                card.HasOwner = false;
            }

            return View(card);
        }

        // POST: RFIDCards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CardNumber,IsActive,HasOwner,Firstname,Lastname,Email,IssueDate,ValidDate")] CardOwnerRFIDCard card)
        {
            if (ModelState.IsValid)
            {
                var rFIDCard = _context.RFIDCards.Include(c => c.CardOwner).FirstOrDefault(c => c.Id == id);
                if (rFIDCard == null)
                    return NotFound();

                rFIDCard.CardNumber = card.CardNumber;
                rFIDCard.IsActive = card.IsActive;

                if (!card.HasOwner)
                {
                    if(rFIDCard.CardOwner != null)
                    {
                        CardOwner cardOwner = rFIDCard.CardOwner;
                        rFIDCard.CardOwner = null;
                        _context.Remove(cardOwner);
                        _context.SaveChanges();
                    }
                }
                else
                {
                    if (rFIDCard.CardOwner != null)
                    {
                        rFIDCard.CardOwner.Firstname = card.Firstname;
                        rFIDCard.CardOwner.Lastname = card.Lastname;
                        rFIDCard.CardOwner.Email = card.Email;
                        rFIDCard.CardOwner.IssueDate = card.IssueDate;
                        rFIDCard.CardOwner.ValidDate = card.ValidDate;
                    }
                    else
                    {
                        CardOwner cardOwner = new();
                        cardOwner.Firstname = card.Firstname;
                        cardOwner.Lastname = card.Lastname;
                        cardOwner.Email = card.Email;
                        cardOwner.IssueDate = card.IssueDate;
                        cardOwner.ValidDate = card.ValidDate;
                        rFIDCard.CardOwner = cardOwner;
                    }
                }
                
                try
                {
                    _context.Update(rFIDCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RFIDCardExists(rFIDCard.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    TempData["duplicateCard"] = true;
                    return View(card);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: RFIDCards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rFIDCard = await _context.RFIDCards
                .Include(c => c.CardOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rFIDCard == null)
            {
                return NotFound();
            }

            return View(rFIDCard);
        }

        // POST: RFIDCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rFIDCard = await _context.RFIDCards.FindAsync(id);

dotnet/iot-parking/iot-parking/Views/RFIDCards/Create.cshtml
@model iot_parking.Models.CardOwnerRFIDCard

@{
    ViewData["Title"] = "Tworzenie karty";
}

<h1>Dodawanie karty</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label">Numer karty</label>
                <div class="row">
                    <input asp-for="CardNumber" class="form-control col-md" />
                    <input type="button" class="btn btn-outline-primary col-sm" value="Zeskanowane karty" onclick="location.href='@Url.Action("PickCard", "RFIDCards")'" />
                </div>
                <span asp-validation-for="CardNumber" class="text-danger"></span>
                @if ((bool)TempData["duplicateCard"])
                {
                    @:<span class="text-danger">Numer karty musi być unikatowy!</span>
                }
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> Aktywna
                </label>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasOwner" onchange="changeHasOwner()" id="hasOwnerCheck" /> Ma właściciela
                </label>
            </div>

            <div class="form-group">
                <label asp-for="Firstname" class="control-label">Imię</label>
                <input asp-for="Firstname" class="form-control owner" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label">Nazwisko</label>
                <input asp-for="Lastname" class="form-control owner" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control owner" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label">Data wydania</label>
                <input asp-for="IssueDate" class="form-control owner" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidDate" class="control-label">Data ważności</label>
                <input asp-for="ValidDate" class="form-control owner" />
                <span asp-validation-for="ValidDate" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    document.addEventListener('DOMContentLoaded', changeHasOwner, false);
</script>
}

dotnet/iot-parking/iot-parking/Views/RFIDCards/Delete.cshtml
@model iot_parking.Models.RFIDCard

@{
    ViewData["Title"] = "Usuwanie karty";
}

<h1>Usuwanie</h1>

<h3>Jesteś pewny, że chcesz usunąć kartę:</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayName("Numer karty")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Aktywna")
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsActive)
            {
                @:Tak
            }
            else
            {
                @:Nie
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Imie")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Nazwisko")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Email")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Data wydania")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.IssueDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Data ważności")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.ValidDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót</a>
    </form>
</div>

dotnet/iot-parking/iot-parking/Views/RFIDCards/Details.cshtml
@model iot_parking.Models.RFIDCard

@{
    ViewData["Title"] = "Datale karty";
}

<h1 class="h1">Detale karty</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayName("Numer karty")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Aktywna")
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsActive)
            {
                @:Tak
            }
            else
            {
                @:Nie
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Imie")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Nazwisko")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Email")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Data wydania")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.IssueDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Data ważności")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CardOwner.ValidDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a> |
    <a asp-action="Index">Powrót</a>
</div>

dotnet/iot-parking/iot-parking/Views/RFIDCards/Edit.cshtml
@model iot_parking.Models.CardOwnerRFIDCard

@{
    ViewData["Title"] = "Edycja karty";
}

<h1 class="h1">Edycja karty</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label">Numer karty</label>
                <div class="row">
                    <input asp-for="CardNumber" class="form-control col-md" value=@ViewBag.cardNr />
                    <input type="button" class="btn btn-outline-primary col-sm" value="Zeskanowane karty" onclick="location.href='@Url.Action("PickCard", "RFIDCards")'" />
                </div>
                <span asp-validation-for="CardNumber" class="text-danger"></span>
                @if ((bool)TempData["duplicateCard"])
                {
                    @:<span class="text-danger">Numer karty musi być unikatowy!</span>
                }
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> Aktywna
                </label>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasOwner" onchange="changeHasOwner()" id="hasOwnerCheck" /> Ma właściciela
                </label>
            </div>

            <div class="form-group">
                <label asp-for="Firstname" class="control-label">Imię</label>
                <input asp-for="Firstname" class="form-control owner" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label">Nazwisko</label>
                <input asp-for="Lastname" class="form-control owner" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control owner" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label">Data wydania</label>
                <input asp-for="IssueDate" class="form-control owner" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValidDate" class="control-label">Data ważności</label>
                <input asp-for="ValidDate" class="form-control owner" />
                <span asp-validation-for="ValidDate" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Edytuj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    document.addEventListener('DOMContentLoaded', changeHasOwner, false);
</script>
}

dotnet/iot-parking/iot-parking/Views/RFIDCards/Index.cshtml
@model IEnumerable<iot_parking.Models.RFIDCard>

@{
    ViewData["Title"] = "Karty";
}
    <h1 class="h1">Karty</h1>
    <input type="button" value="Dodaj nową" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "RFIDCards")'" />
<hr/>
<form asp-action="Index" method="get">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <input type="submit" class="btn btn-outline-primary" value="Wyszukaj" />
            <input type="button" value="x" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "RFIDCards")'" />
        </div>
        <input type="text" name="search" id="search-box" class="form-control" />
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Nr karty")
            </th>
            <th>
                @Html.DisplayName("Aktywna")
            </th>
            <th>
                @Html.DisplayName("Imie")
            </th>
            <th>
                @Html.DisplayName("Nazwisko")
            </th>
            <th>
                @Html.DisplayName("Email")
            </th>
            <th>
                @Html.DisplayName("Data wydania")
            </th>
            <th>
                @Html.DisplayName("Data ważności")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (RFIDCard item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CardNumber)
            </td>
            <td>
                @if (item.IsActive)
                {
                    @:Tak
                }
                else
                {
                    @:Nie
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardOwner.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardOwner.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardOwner.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardOwner.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardOwner.ValidDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detale</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>

dotnet/iot-parking/iot-parking/Views/RFIDCards/PickCard.cshtml
@model IEnumerable<iot_parking.Models.ScannedCard>

@{
    ViewData["Title"] = "Wybór karty";
}

<h1 class="h1">Wybierz kartę</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Nr karty")
            </th>
            <th>
                @Html.DisplayName("Data dodania")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (ScannedCard item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScanDate)
                </td>
                <td>
                    <input type="button" class="btn btn-outline-primary" value="Wybierz" 
                           onclick="location.href='@Url.Action(TempData["pickCard"].ToString(), "RFIDCards", new { id = TempData["carId"], cardId = item.Id })'" />
                </td>
            </tr>
        }
    </tbody>
</table>